"""CLI entrypoints for agent, benchmarks, and evaluation."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from reasoning_agent.agent.runner import AgentRunner
from reasoning_agent.evaluation import BenchmarkRunner, BenchmarkVisualizer
from reasoning_agent.schemas import ReasoningMode
from reasoning_agent.settings import load_settings
from reasoning_agent.utils.json_utils import dumps


def _chat_command(args: argparse.Namespace) -> int:
    settings = load_settings(args.config)
    runner = AgentRunner(settings=settings)

    session_id = args.session_id
    try:
        response = runner.run(session_id=session_id, user_input=args.prompt, mode=ReasoningMode.REACT)
        print(response.answer)
        if args.json:
            print(dumps(response.model_dump(), indent=True))
    finally:
        runner.close()
    return 0


def _benchmark_command(args: argparse.Namespace) -> int:
    settings = load_settings(args.config)
    runner = BenchmarkRunner(settings)
    result = runner.run(output_dir=args.output_dir)

    visualizer = BenchmarkVisualizer(output_dir="artifacts/plots")
    visualizer.generate_all(result["summary"])

    print(dumps(result["summary"], indent=True))
    return 0


def _evaluate_command(args: argparse.Namespace) -> int:
    settings = load_settings(args.config)
    report_path = Path(args.output)
    report_path.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "message": "Evaluation report generated by benchmark pipeline.",
        "dataset": settings.benchmark_dataset_path,
        "output_dir": settings.benchmark_output_dir,
    }
    report_path.write_text(dumps(payload, indent=True), encoding="utf-8")
    print(f"wrote {report_path}")
    return 0


def build_parser() -> argparse.ArgumentParser:
    """Build CLI parser."""

    parser = argparse.ArgumentParser(description="Production AI Reasoning Agent CLI")
    parser.add_argument("--config", default="configs/config.yaml")

    sub = parser.add_subparsers(dest="command", required=True)

    chat = sub.add_parser("chat", help="Run single chat prompt")
    chat.add_argument("prompt")
    chat.add_argument("--session-id", default="cli-session")
    chat.add_argument("--json", action="store_true")
    chat.set_defaults(func=_chat_command)

    bench = sub.add_parser("benchmark", help="Run full benchmark")
    bench.add_argument("--output-dir", default="artifacts/reports")
    bench.set_defaults(func=_benchmark_command)

    evaluate = sub.add_parser("evaluate", help="Write evaluation report marker")
    evaluate.add_argument("--output", default="artifacts/reports/evaluation_report.json")
    evaluate.set_defaults(func=_evaluate_command)

    return parser


def main(argv: list[str] | None = None) -> int:
    """Main CLI entrypoint."""

    parser = build_parser()
    args = parser.parse_args(argv)
    return int(args.func(args))


def chat_main() -> None:
    """Script wrapper for chat command."""

    sys.exit(main(["chat", *sys.argv[1:]]))


def benchmark_main() -> None:
    """Script wrapper for benchmark command."""

    sys.exit(main(["benchmark", *sys.argv[1:]]))


def evaluate_main() -> None:
    """Script wrapper for evaluate command."""

    sys.exit(main(["evaluate", *sys.argv[1:]]))


if __name__ == "__main__":
    raise SystemExit(main())
