"""Project-level utility helpers."""

from __future__ import annotations

import json
import logging
import random
import shutil
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
from joblib import dump, load

from .config import FIGURES_DIR, MODELS_DIR, OUTPUTS_DIR, REPORTS_DIR, TABLES_DIR


def configure_logging(level: int = logging.INFO) -> None:
    """Configure root logging once for CLI and notebook usage."""
    logging.basicConfig(
        level=level,
        format="%(asctime)s | %(levelname)s | %(name)s | %(message)s",
    )
    logging.getLogger("matplotlib").setLevel(logging.WARNING)


def set_global_seed(seed: int) -> None:
    """Set deterministic seed for Python and NumPy."""
    random.seed(seed)
    np.random.seed(seed)


def ensure_output_dirs() -> None:
    """Create all output directories used by the workflow."""
    for path in [OUTPUTS_DIR, FIGURES_DIR, REPORTS_DIR, TABLES_DIR, MODELS_DIR]:
        path.mkdir(parents=True, exist_ok=True)


def save_dataframe(df: pd.DataFrame, path: Path) -> Path:
    """Persist a DataFrame to CSV and return file path."""
    path.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(path, index=False)
    return path


def save_json(payload: dict[str, Any], path: Path) -> Path:
    """Persist structured JSON report to disk."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, default=str))
    return path


def save_model(model: Any, path: Path) -> Path:
    """Serialize model artifact using joblib."""
    path.parent.mkdir(parents=True, exist_ok=True)
    dump(model, path)
    return path


def load_model(path: Path) -> Any:
    """Load serialized model artifact using joblib."""
    return load(path)


def cleanup_runtime_artifacts(project_root: Path) -> None:
    """Remove known transient runtime artifacts generated by third-party libraries."""
    for rel in ["catboost_info", "logs.log"]:
        path = project_root / rel
        if path.is_dir():
            shutil.rmtree(path, ignore_errors=True)
        elif path.exists():
            path.unlink(missing_ok=True)
