"""Advanced analytics helpers."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

import numpy as np
import pandas as pd


@dataclass(slots=True)
class SchemaField:
    """Inferred schema field."""

    name: str
    inferred_type: str
    nullable: bool
    semantic_label: str


class AdvancedAnalyticsEngine:
    """Advanced layer: schema inference, NL filters, joins, trend/forecast/clustering."""

    SEMANTIC_HINTS = {
        "date": ["date", "day", "month", "quarter", "year"],
        "revenue": ["revenue", "sales", "amount", "gmv", "income"],
        "customer": ["customer", "user", "client", "buyer"],
        "product": ["product", "item", "sku", "category"],
        "cost": ["cost", "expense", "spend"],
        "region": ["region", "country", "city", "state", "market"],
    }

    def infer_schema(self, df: pd.DataFrame) -> list[SchemaField]:
        """Infer typed schema and semantic label for dataframe columns."""
        fields: list[SchemaField] = []
        for column in df.columns:
            series = df[column]
            inferred_type = self._infer_type(series)
            semantic = self._semantic_label(column)
            fields.append(
                SchemaField(
                    name=column,
                    inferred_type=inferred_type,
                    nullable=bool(series.isna().any()),
                    semantic_label=semantic,
                )
            )
        return fields

    def business_glossary(self, df: pd.DataFrame) -> dict[str, str]:
        """Generate business glossary from semantic labels."""
        glossary: dict[str, str] = {}
        for field in self.infer_schema(df):
            if field.semantic_label == "revenue":
                glossary[field.name] = "Monetary value generated by sales or transactions."
            elif field.semantic_label == "customer":
                glossary[field.name] = "Identifier or attribute representing customers."
            elif field.semantic_label == "product":
                glossary[field.name] = "Product or SKU reference used in transactions."
            elif field.semantic_label == "date":
                glossary[field.name] = "Time reference used for period and trend analysis."
            elif field.semantic_label == "cost":
                glossary[field.name] = "Monetary spending or operational expense metric."
            elif field.semantic_label == "region":
                glossary[field.name] = "Geographic segmentation dimension."
            else:
                glossary[field.name] = "General analytical field with no domain-specific semantic hint."
        return glossary

    def natural_language_filter(self, df: pd.DataFrame, query: str) -> pd.DataFrame:
        """Apply basic natural-language filters.

        Supported patterns:
        - `where <column> = <value>`
        - `top N by <column>`
        - `after YYYY-MM-DD` (detected date column)
        """
        lower = query.lower().strip()
        out = df.copy()

        if " where " in f" {lower} " and "=" in lower:
            clause = lower.split("where", maxsplit=1)[1].strip()
            left, right = clause.split("=", maxsplit=1)
            col_name = left.strip()
            value = right.strip().strip("'\"")
            matched_col = next((col for col in out.columns if col.lower() == col_name), None)
            if matched_col:
                return out[out[matched_col].astype(str).str.lower() == value.lower()]

        if lower.startswith("top ") and " by " in lower:
            tokens = lower.split()
            try:
                n = int(tokens[1])
            except Exception:  # noqa: BLE001
                n = 5
            metric_name = lower.split(" by ", maxsplit=1)[1].strip()
            metric_col = next((col for col in out.columns if col.lower() == metric_name), None)
            if metric_col:
                out[metric_col] = pd.to_numeric(out[metric_col], errors="coerce")
                return out.nlargest(n, metric_col)

        if "after" in lower:
            date_col = self._first_date_col(out)
            if date_col:
                token = lower.split("after", maxsplit=1)[1].strip().split()[0]
                cutoff = pd.to_datetime(token, errors="coerce", format="mixed")
                if pd.notna(cutoff):
                    parsed = pd.to_datetime(out[date_col], errors="coerce", format="mixed")
                    return out[parsed > cutoff]

        return out

    def cross_sheet_join(
        self,
        frames: dict[str, pd.DataFrame],
        left_key: str,
        right_key: str,
        how: str = "left",
    ) -> pd.DataFrame:
        """Join first two frames for multi-sheet reasoning."""
        keys = list(frames.keys())
        if len(keys) < 2:
            return pd.DataFrame()
        left_df = frames[keys[0]]
        right_df = frames[keys[1]]
        if left_key not in left_df.columns or right_key not in right_df.columns:
            return pd.DataFrame()
        return left_df.merge(right_df, left_on=left_key, right_on=right_key, how=how)

    def detect_trend(self, df: pd.DataFrame, date_col: str, value_col: str) -> dict[str, Any]:
        """Detect trend direction from time series."""
        work = df.copy()
        work[date_col] = pd.to_datetime(work[date_col], errors="coerce", format="mixed")
        work[value_col] = pd.to_numeric(work[value_col], errors="coerce")
        work = work.dropna(subset=[date_col, value_col]).sort_values(date_col)
        if len(work) < 3:
            return {"available": False, "reason": "insufficient rows"}

        x = np.arange(len(work))
        y = work[value_col].to_numpy()
        slope, intercept = np.polyfit(x, y, 1)
        trend = "upward" if slope > 0 else "downward" if slope < 0 else "flat"
        return {
            "available": True,
            "trend": trend,
            "slope": float(slope),
            "intercept": float(intercept),
        }

    def forecast(self, df: pd.DataFrame, date_col: str, value_col: str, periods: int = 3) -> list[dict[str, Any]]:
        """Simple linear forecast for next periods."""
        work = df.copy()
        work[date_col] = pd.to_datetime(work[date_col], errors="coerce", format="mixed")
        work[value_col] = pd.to_numeric(work[value_col], errors="coerce")
        work = work.dropna(subset=[date_col, value_col]).sort_values(date_col)
        if len(work) < 4:
            return []

        x = np.arange(len(work))
        y = work[value_col].to_numpy()
        slope, intercept = np.polyfit(x, y, 1)

        last_date = work[date_col].max()
        step = (work[date_col].diff().dropna().median() or pd.Timedelta(days=30))
        out: list[dict[str, Any]] = []
        for i in range(1, periods + 1):
            idx = len(work) + i - 1
            forecast_value = slope * idx + intercept
            out.append(
                {
                    "period": i,
                    "date": (last_date + step * i).strftime("%Y-%m-%d"),
                    "forecast": float(forecast_value),
                }
            )
        return out

    def cluster(self, df: pd.DataFrame, value_col: str, n_clusters: int = 3) -> pd.DataFrame:
        """Cluster values using quantile buckets (dependency-light fallback)."""
        work = df.copy()
        work[value_col] = pd.to_numeric(work[value_col], errors="coerce")
        non_null = work.dropna(subset=[value_col]).copy()
        if non_null.empty:
            return pd.DataFrame()

        bins = min(n_clusters, non_null[value_col].nunique())
        if bins < 2:
            non_null["cluster"] = 0
            return non_null

        non_null["cluster"] = pd.qcut(non_null[value_col], q=bins, labels=False, duplicates="drop")
        return non_null

    def _infer_type(self, series: pd.Series) -> str:
        if pd.api.types.is_numeric_dtype(series):
            return "numeric"
        if pd.api.types.is_datetime64_any_dtype(series):
            return "datetime"
        parsed_date = pd.to_datetime(series, errors="coerce", format="mixed")
        if parsed_date.notna().sum() >= max(5, int(0.5 * len(series.dropna()))):
            return "datetime"
        parsed_num = pd.to_numeric(series, errors="coerce")
        if parsed_num.notna().sum() >= max(5, int(0.5 * len(series.dropna()))):
            return "numeric"
        return "categorical"

    def _semantic_label(self, column_name: str) -> str:
        lowered = column_name.lower()
        for label, hints in self.SEMANTIC_HINTS.items():
            if any(hint in lowered for hint in hints):
                return label
        return "unknown"

    def _first_date_col(self, df: pd.DataFrame) -> str | None:
        for col in df.columns:
            parsed = pd.to_datetime(df[col], errors="coerce", format="mixed")
            if parsed.notna().sum() >= max(5, int(0.5 * len(df[col].dropna()))):
                return col
        return None
