"""Feature specification for the curated Ames Housing API track."""

from __future__ import annotations

NUMERIC_FEATURES: list[str] = [
    "lot_frontage",
    "lot_area",
    "overall_qual",
    "overall_cond",
    "year_built",
    "year_remod_add",
    "mas_vnr_area",
    "bsmt_fin_sf_1",
    "bsmt_fin_sf_2",
    "bsmt_unf_sf",
    "total_bsmt_sf",
    "first_flr_sf",
    "second_flr_sf",
    "low_qual_fin_sf",
    "gr_liv_area",
    "bsmt_full_bath",
    "bsmt_half_bath",
    "full_bath",
    "half_bath",
    "bedroom_abv_gr",
    "kitchen_abv_gr",
    "tot_rms_abv_grd",
    "fireplaces",
    "garage_yr_blt",
    "garage_cars",
    "garage_area",
    "wood_deck_sf",
    "open_porch_sf",
    "enclosed_porch",
    "three_ssn_porch",
    "screen_porch",
    "pool_area",
    "misc_val",
    "mo_sold",
    "yr_sold",
    "ms_subclass",
]

CATEGORICAL_FEATURES: list[str] = [
    "ms_zoning",
    "street",
    "lot_shape",
    "land_contour",
    "utilities",
    "lot_config",
    "land_slope",
    "neighborhood",
    "condition_1",
    "bldg_type",
    "house_style",
    "roof_style",
    "exterior_1st",
    "exterior_2nd",
    "exter_qual",
    "exter_cond",
    "foundation",
    "bsmt_qual",
    "bsmt_cond",
    "bsmt_exposure",
    "bsmt_fin_type_1",
    "bsmt_fin_type_2",
    "heating",
    "heating_qc",
    "central_air",
    "electrical",
    "kitchen_qual",
    "functional",
    "fireplace_qu",
    "garage_type",
    "garage_finish",
    "garage_qual",
    "garage_cond",
    "paved_drive",
    "sale_type",
    "sale_condition",
]

ALL_FEATURES: list[str] = NUMERIC_FEATURES + CATEGORICAL_FEATURES
TARGET_COLUMN: str = "sale_price"

DEFAULT_CATEGORY_VALUES: dict[str, list[str]] = {
    "ms_zoning": ["RL", "RM", "FV", "RH"],
    "street": ["Pave", "Grvl"],
    "lot_shape": ["Reg", "IR1", "IR2"],
    "land_contour": ["Lvl", "Bnk", "HLS"],
    "utilities": ["AllPub", "NoSeWa"],
    "lot_config": ["Inside", "Corner", "CulDSac", "FR2"],
    "land_slope": ["Gtl", "Mod", "Sev"],
    "neighborhood": ["NAmes", "CollgCr", "OldTown", "Edwards", "Somerst"],
    "condition_1": ["Norm", "Feedr", "Artery"],
    "bldg_type": ["1Fam", "TwnhsE", "Duplex"],
    "house_style": ["1Story", "2Story", "1.5Fin"],
    "roof_style": ["Gable", "Hip", "Flat"],
    "exterior_1st": ["VinylSd", "HdBoard", "Wd Sdng", "MetalSd"],
    "exterior_2nd": ["VinylSd", "Plywood", "Wd Sdng", "MetalSd"],
    "exter_qual": ["Ex", "Gd", "TA", "Fa"],
    "exter_cond": ["Ex", "Gd", "TA", "Fa"],
    "foundation": ["PConc", "CBlock", "BrkTil", "Slab"],
    "bsmt_qual": ["Ex", "Gd", "TA", "Fa"],
    "bsmt_cond": ["Ex", "Gd", "TA", "Fa"],
    "bsmt_exposure": ["Gd", "Av", "Mn", "No"],
    "bsmt_fin_type_1": ["GLQ", "ALQ", "BLQ", "Rec", "LwQ", "Unf"],
    "bsmt_fin_type_2": ["GLQ", "ALQ", "BLQ", "Rec", "LwQ", "Unf"],
    "heating": ["GasA", "GasW", "Grav"],
    "heating_qc": ["Ex", "Gd", "TA", "Fa"],
    "central_air": ["Y", "N"],
    "electrical": ["SBrkr", "FuseA", "FuseF"],
    "kitchen_qual": ["Ex", "Gd", "TA", "Fa"],
    "functional": ["Typ", "Min1", "Min2", "Maj1"],
    "fireplace_qu": ["Ex", "Gd", "TA", "Fa", "Po"],
    "garage_type": ["Attchd", "Detchd", "BuiltIn", "CarPort"],
    "garage_finish": ["Fin", "RFn", "Unf"],
    "garage_qual": ["Ex", "Gd", "TA", "Fa", "Po"],
    "garage_cond": ["Ex", "Gd", "TA", "Fa", "Po"],
    "paved_drive": ["Y", "P", "N"],
    "sale_type": ["WD", "New", "COD", "ConLD"],
    "sale_condition": ["Normal", "Partial", "Abnorml", "Family"],
}
